# DigitalOcean App Platform Configuration
name: elgasmi-eu
region: fra

services:
  - name: web
    github:
      repo: elgasmi/elgasmi-eu
      branch: main
      deploy_on_push: true
    build_command: pnpm install && pnpm run build
    run_command: pnpm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ENCRYPTION_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
